config/routes.rb
Rails.application.routes.draw do
  resources :drink_orders do
    resources :drinks
    
  end
  resources :drinks do 
    resources :drink_orders
    get :current_user_drinks_order, on: :collection
    get :current_user_drinks, on: :collection
  end 
  
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'} 
    
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "drinks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
    has_many :drink_orders
    has_many :users, through: :drink_orders, counter_cache: true
    validates :name, :ingredients, :price, presence: true

    def self.default_scope
        order(:name => "ASC")
    end

end

app/models/drink_order.rb
class DrinkOrder < ApplicationRecord
  belongs_to :user
  belongs_to :drink 
  
  validates :user_id, :drink_id, :special_instructions, :quantity, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :drink_orders
  has_many :drinks, through: :drink_orders
  devise :database_authenticatable, :registerable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  validates :date_of_birth, :presence => true
  validate :validate_age
  private
  def validate_age
    if date_of_birth.present? && date_of_birth > 21.years.ago.to_date
        errors.add(:date_of_birth, 'You should be over 21 years old.')
    end
  end

  #validates oauth
  def self.from_google(uid:, email:, full_name:, avatar_url:)
  user = User.find_or_create_by(email: email) do |u|
    u.uid = uid
    u.full_name = full_name
    u.avatar_url = avatar_url
    u.password = SecureRandom.hex
  end
    user.update(uid: uid, full_name: full_name, avatar_url: avatar_url)
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    #before_action :authenticate_admin!#, only: [:action]
    rescue_from ActiveRecord::RecordNotFound, with: :not_found 

    def not_found
        flash[:error] = "Not Found"
        redirect_to root_path
    end 

    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:date_of_birth])
    end

    #def authenticate_admin? 
    #    authenticate_user!
    #    redirect_to :login, #status::forbidden unless #current_user.admin?
    #end
end

app/controllers/drink_orders_controller.rb
class DrinkOrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_drink
  before_action :authenticate_user!
  

  def index
    @orders = @drink.drink_orders
  
  end

  def new
    @order = DrinkOrder.new
    if @drink
      @id = @drink.id
    else
      @id = nil
    end
  end

  def show
    @orders = current_user.drink_orders.find(params[:id])
  end

  def edit
    
  end

  def create
    @order = current_user.drink_orders.build(drink_order_params)
    #@order.drink.id = @drink.id
    if @order.save
      redirect_to current_user_drinks_order_drinks_path(@order)
    else
      render :new
    end
  end

  def update
    if @order.update(drink_order_params)
      redirect_to drink_order_path(@order)
    else
      render :edit 
    end
  end

  def destroy
   @order.destroy
   redirect_to drinks_path
  end

  private

  def set_order
    @order = DrinkOrder.find(params[:id])
  end
  
  def set_drink
    @drink = Drink.find_by_id(params[:drink_id])
  end

  def drink_order_params
    params.require(:drink_order).permit(:user_id, :drink_id, :special_instructions, :quantity, :name)
  end 


end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_drink, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 

  def index
    @drinks = Drink.all  
  end

  def current_user_drinks_order
    @orders = current_user.drink_orders
  end

  def current_user_drinks 
    @drinks = current_user.drinks
  end 

  def new
    @drink = Drink.new
  end

  def show
    
  end

  def edit
    
  end

  def create
    @drink = current_user.drinks.build(drink_params)
    if @drink.save
      redirect_to drink_path(@drink)
    else
      render :new
    end
  end

  def update
    if @drink.update(drink_params)
      redirect_to drink_path(@drink)
    else
      render :edit 
    end
  end

  def destroy
   @drink.destroy
   redirect_to drinks_path
  end

  private
  def set_drink
    @drink = Drink.find(params[:id])
  end 

  def drink_params
    params.require(:drink).permit(:name, :ingredients, :price)
  end 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :set_order, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!

def index
    @orders = Order.all #not sure why i can't use current_user.orders here  
end

def new
   @order = Order.new
end

def show
  @orders = current_user.orders.find(params[:id])
end

def edit
set_order
end

def create
  @order = current_user.orders.build(order_params)
  if @order.save
    redirect_to order_path(@order)
  else
    render :new
  end
end

def update
   if @order.update(order_params)
     redirect_to order_path(@order)
   else
     render :edit 
   end
end

def destroy
 @order.destroy
 redirect_to orders_path
end

private

def set_order
    @order = Order.find(params[:id])
end 

def order_params
    params.require(:order).permit(:quantity)
end 
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    
    def google_oauth2
      user = User.from_google(from_google_params)
      
      if user.present?
        sign_out_all_scopes
        flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect user, event: :authentication
      else
        flash[:alert] = t 'devise.omniauth_callbacks.failure', kind: 'Google',reason: "#{auth.info.email} is not authorized."
        redirect_to new_user_session_path
      end
    end
    
    protected
    
    def after_omniauth_failure_path_for(_scope)
      new_user_session_path
    end
    
    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || root_path
    end
    
    private
    
    def from_google_params
      @from_google_params ||= {
        uid: auth.uid,
        email: auth.info.email,
        full_name: auth.info.name,
        avatar_url: auth.info.image
      }
    end
    
    def auth
      @auth ||= request.env['omniauth.auth']
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drink_orders_helper.rb
module DrinkOrdersHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper 
    def show_errors_for(object)
        render partial: 'errors/errors', locals: {object: object} 
    end
end 

app/views/drink_orders/_form.html.erb
<%= show_errors_for(@order)%>
<%= form_for ([@drink, @order]) do |f| %>

<%= collection_select(:drink_order, :drink_id, Drink.all, :id, :name, prompt: true, selected: @id)
 %>
<%= f.label :special_instructions, "Instructions" %>
<%= f.text_field :special_instructions %>

<%= f.label :quantity, "Quantity" %>
<%= f.text_field :quantity %>
<%= f.submit %>
<%= link_to "Back", drinks_path %>|

<% end %>

app/views/drink_orders/edit.html.erb
<h1>Edit Page</h1>

<%= render partial: 'form', locals: {drink_order: @order} %>
<%= link_to "Back", drink_order_path(@order) %>|

app/views/drink_orders/index.html.erb
<h1> <%= @drink.name %> Orders </h1>

<ol><% @orders.each do |order|%>
<li><%= order.drink.name %>
<%= order.quantity %>
<%= order.special_instructions %></li>
<% end %></ol>
<%= link_to "Create Order", new_drink_drink_order_path(@drink) %>|
<%= link_to "Drink Menu", drinks_path %>|

app/views/drink_orders/new.html.erb
<%= render partial: 'form', locals: {drink_order: @order} %>

app/views/drink_orders/show.html.erb
<h1>Order Information</h1>
<%= @order.drink.name %>
<%= @order.quantity %>
<%= @order.special_instructions %>
<%= link_to "Edit Order", edit_drink_order_path(@order) %>
<%= form_tag(drink_order_path(@order), method: :delete, style: 'display: inline-block;') do %>
    <%= submit_tag "Delete Order" %>
<% end %>

app/views/drinks/_form.html.erb
<%= show_errors_for(drink)%>
<%= form_for drink do |f| %>
<%= f.label :name, "Drink Name" %>
<%= f.text_field :name %>
<%= f.label :ingredients, "Ingredients" %>
<%= f.text_field :ingredients %>
<%= f.label :price, "Drink Price" %>
<%= f.text_field :price %>

<%= f.submit %>
<% end %>

app/views/drinks/current_user_drinks.html.erb
<h3>My Drinks</h3>

<% @drinks.each do |drink|%>
    
  <strong>Drink:</strong>
  <%= link_to drink.name, drink_path(drink) %><br>
  <br>
    
<% end %>

app/views/drinks/current_user_drinks_order.html.erb
<h3> My Orders</h3>
<% @orders.each do |order|%>
<li><%= link_to order.drink.name, drink_order_path(order) %> , Qty:
<%= order.quantity %>, Special Instructions:
<%= order.special_instructions %>
<% end %></li><br>

<%= link_to "Back ", new_drink_order_path %>|
<%= link_to "Drink Menu ", drinks_path %>|

app/views/drinks/edit.html.erb
<h1>Edit Drink</h1>

<%= render partial: 'form', locals: {drink: @drink} %>
<%= link_to "Back", drink_path(@drink) %>|

app/views/drinks/index.html.erb
<h1> Drinks </h1>

<% Drink.all.each do |drink|%>
    
  <strong>Drink:</strong>
  <%= link_to drink.name, drink_path(drink) %><br>
  <br>
    
<% end %>
    

app/views/drinks/new.html.erb
<h1>New Drinks</h1>
<%= render partial: 'form', locals: {drink: @drink} %>
 <%= link_to "Back", drinks_path %>|

app/views/drinks/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @drink.name %>
</p>
<p>
  <strong>Ingredients:</strong>
  <%= @drink.ingredients %>
</p>
<p>
  <strong>Price:</strong>
  <%= @drink.price %>
</p><br>

<%= link_to "Back", drinks_path %>|

<%= link_to "Order Drink", new_drink_drink_order_path(@drink) %>|
<%= link_to "All Orders For This Drink", drink_drink_orders_path(@drink) %>|

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MobileBartending</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'navbar/navbar' %>

  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/navbar/_navbar.html.erb
<nav>
    <% if user_signed_in? %>
    <%= link_to "Drinks", drinks_path  %> |
    <%= link_to "My Drinks", current_user_drinks_drinks_path %> |
    <%= link_to "My Orders", current_user_drinks_order_drinks_path %> |    

    <%= form_tag(destroy_user_session_path, method: :delete, style: "display: inline-block") do %>

    <%=submit_tag "Sign out" %>
    <% end %>
    <% else %>
    <%= link_to "Sign Up", new_user_registration_path %>
    <%= link_to "Sign In", new_user_session_path %>

    <% end %>
</nav>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %></h1>